### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by ryukzak** [ryukzak/course-bot#4]
Problem: project contains a lot of hardcoded lines on a mix of Russian and English languages.

We need to fix that in two ways:

- use English as a default language (and for tests)
- add the possibility to provide the Russian language as an option for the whole bot.

How we can perform this:

- Add multi-language support: https://github.com/ryukzak/course-bot/pull/20
- Specific example of how to avoid "hardcoded strings" and add translation: https://github.com/ryukzak/course-bot/pull/20/commits/75ebc76560b6941fb501602533d18f4795bce010
- `format` https://github.com/ryukzak/course-bot/commit/ee2a977dff0acf96bdd4f48c074dcd1c3b71abe8
PR requirements:

- all PR should be tested before submission. 
- test should be in English (if not -- translate and fix them)
- do not make huge PRs, because it will be too hard to review. Make it talk by talk.

**Comment by vladhacksmile** [comment]
I took this task
