### ISSUE TITLE
Меню команд, грамматическая ошибка.

### ISSUE THREAD

**Issue by visvaldas01** [ryukzak/course-bot#8]
"Test already runned" в quiz.clj и тестах (не исправил, так как не понял, что подразумевалось).
В меню команд (слева от эмодзи) часть команд отсутствует (как минимум help, renameme, lab1soon и quiz).

**Comment by ryukzak** [comment]
Please, write your report in English, as other issues in this repo. Also, don't understand what you means about "Test already runned". Need more context.

Don't describe two different problem in one issue. About second: it is not a code problemt.

**Comment by Vsevolod01** [comment]
![image](https://user-images.githubusercontent.com/60853667/194291546-a3814e66-8012-45a1-b860-5a331a0b93f7.png)

**Comment by ryukzak** [comment]
"The test is already running. Only one test at a time."

**Comment by ryukzak** [comment]
Better place for such things -- PR. Thank you for your attention!
